<?php

namespace App\Services;

use Illuminate\Support\Facades\Log;

class WebServerConfigService
{
    /**
     * Update web server configuration for Cloudflare
     */
    public function updateConfig(): bool
    {
        $serverType = $this->detectWebServer();
        $ipRanges = app(CloudflareService::class)->getIpRanges();

        switch ($serverType) {
            case 'nginx':
                return $this->updateNginxConfig($ipRanges);
            case 'apache':
                return $this->updateApacheConfig($ipRanges);
            default:
                Log::warning('Web server not detected, skipping config update');
                return false;
        }
    }

    /**
     * Detect web server type
     */
    private function detectWebServer(): ?string
    {
        if (file_exists('/etc/nginx/nginx.conf')) {
            return 'nginx';
        }

        if (function_exists('apache_get_version')) {
            return 'apache';
        }

        if (file_exists('/etc/apache2/apache2.conf') || file_exists('/etc/httpd/conf/httpd.conf')) {
            return 'apache';
        }

        return null;
    }

    /**
     * Update Nginx configuration
     */
    private function updateNginxConfig(array $ipRanges): bool
    {
        $configPath = '/etc/nginx/conf.d/cloudflare.conf';
        $backupPath = '/etc/nginx/conf.d/cloudflare.conf.backup';

        $config = $this->generateNginxConfig($ipRanges);

        try {
            // Create backup if exists
            if (file_exists($configPath)) {
                copy($configPath, $backupPath);
            }

            // Write new config
            $result = file_put_contents($configPath, $config, LOCK_EX);

            if ($result !== false) {
                // Test nginx config
                $testResult = shell_exec('nginx -t 2>&1');

                if (str_contains($testResult, 'successful')) {
                    // Reload nginx
                    shell_exec('systemctl reload nginx 2>/dev/null || service nginx reload 2>/dev/null || true');
                    Log::info('Nginx Cloudflare config updated successfully');
                    return true;
                } else {
                    // Restore backup
                    if (file_exists($backupPath)) {
                        copy($backupPath, $configPath);
                    }
                    Log::error('Nginx config test failed: ' . $testResult);
                    return false;
                }
            }

            return false;
        } catch (\Exception $e) {
            Log::error('Failed to update Nginx config: ' . $e->getMessage());
            return false;
        }
    }

    /**
     * Update Apache configuration
     */
    private function updateApacheConfig(array $ipRanges): bool
    {
        $configPath = '/etc/apache2/conf.d/cloudflare.conf';

        // Try alternative paths
        if (!is_writable('/etc/apache2/conf.d/')) {
            $configPath = '/etc/apache2/conf-available/cloudflare.conf';
        }

        if (!is_writable('/etc/apache2/conf-available/')) {
            $configPath = '/etc/httpd/conf.d/cloudflare.conf';
        }

        $config = $this->generateApacheConfig($ipRanges);

        try {
            $result = file_put_contents($configPath, $config, LOCK_EX);

            if ($result !== false) {
                // Test apache config
                $testResult = shell_exec('apachectl configtest 2>&1');

                if (str_contains($testResult, 'Syntax OK') || str_contains($testResult, 'OK')) {
                    // Reload apache
                    shell_exec('systemctl reload apache2 2>/dev/null || systemctl reload httpd 2>/dev/null || service apache2 reload 2>/dev/null || true');
                    Log::info('Apache Cloudflare config updated successfully');
                    return true;
                } else {
                    Log::error('Apache config test failed: ' . $testResult);
                    return false;
                }
            }

            return false;
        } catch (\Exception $e) {
            Log::error('Failed to update Apache config: ' . $e->getMessage());
            return false;
        }
    }

    /**
     * Generate Nginx config content
     */
    private function generateNginxConfig(array $ipRanges): string
    {
        $ipv4Ranges = implode(";\nset_real_ip_from ", $ipRanges['ipv4']);
        $ipv6Ranges = implode(";\nset_real_ip_from ", $ipRanges['ipv6']);

        return <<<NGINX
# Cloudflare IP Ranges - Auto-generated by Paymenter
# Last updated: {$this->getTimestamp()}

# IPv4 ranges
set_real_ip_from {$ipv4Ranges};

# IPv6 ranges
set_real_ip_from {$ipv6Ranges};

# Use Cloudflare's CF-Connecting-IP header
real_ip_header CF-Connecting-IP;

# Optional: Trust X-Forwarded-For as fallback
# real_ip_header X-Forwarded-For;
# real_ip_recursive on;
NGINX;
    }

    /**
     * Generate Apache config content
     */
    private function generateApacheConfig(array $ipRanges): string
    {
        $ipv4Ranges = implode("\nRemoteIPInternalProxy ", $ipRanges['ipv4']);
        $ipv6Ranges = implode("\nRemoteIPInternalProxy ", $ipRanges['ipv6']);

        return <<<APACHE
# Cloudflare IP Ranges - Auto-generated by Paymenter
# Last updated: {$this->getTimestamp()}

<IfModule mod_remoteip.c>
    # Use Cloudflare's CF-Connecting-IP header
    RemoteIPHeader CF-Connecting-IP

    # IPv4 ranges
    RemoteIPInternalProxy {$ipv4Ranges}

    # IPv6 ranges
    RemoteIPInternalProxy {$ipv6Ranges}
</IfModule>
APACHE;
    }

    /**
     * Get current timestamp
     */
    private function getTimestamp(): string
    {
        return date('Y-m-d H:i:s');
    }

    /**
     * Get current config status
     */
    public function getConfigStatus(): array
    {
        $serverType = $this->detectWebServer();
        $configExists = false;
        $configPath = null;

        if ($serverType === 'nginx') {
            $configPath = '/etc/nginx/conf.d/cloudflare.conf';
            $configExists = file_exists($configPath);
        } elseif ($serverType === 'apache') {
            $paths = [
                '/etc/apache2/conf.d/cloudflare.conf',
                '/etc/apache2/conf-available/cloudflare.conf',
                '/etc/httpd/conf.d/cloudflare.conf',
            ];
            foreach ($paths as $path) {
                if (file_exists($path)) {
                    $configPath = $path;
                    $configExists = true;
                    break;
                }
            }
        }

        return [
            'server_type' => $serverType,
            'config_exists' => $configExists,
            'config_path' => $configPath,
            'last_updated' => $configExists ? date('Y-m-d H:i:s', filemtime($configPath)) : null,
        ];
    }
}
